const { v4: uuidv4 } = require('uuid');

/** Define answer class for each answer
 *  @kind Class
 *  @type Model
 */

module.exports = class Answer {
  /** Construct answer object
   *  @param {String} id - the question autogenerated id
   *  @param {String} answer - The answer string
   *  @param {String} parentQuestionID - The ID of the Question the answer belongs to
   */

  constructor(answer, parentQuestionID) {
    this._id = uuidv4();
    this._answer = answer;
    this._ratings = [];
    this._parentQuestionID = parentQuestionID;
    this._comments = [];
  }

  mapToModel() {
    return {
      answer: this._answer,
      ratings: this._ratings,
      parent_id: this._parentQuestionID,
      id: this._id,
      comments: this._comments,
    };
  }
};
