const { v4: uuidv4 } = require('uuid');

/** Define Question class for each Question
 *  @kind Class
 *  @type Model
 */

class Question {
  /** Construct answer object
   *  @param {String} id - the question autogenerated id
   *  @param {String} answer - The answer string
   *  @param {String} parentQuestionID - The ID of the Question the answer belongs to
   */
  constructor(question, categories) {
    this._id = uuidv4();
    this._question = question;
    this._ratings = [];
    this._answers = [];
    this._categories = Array.isArray(categories) ? categories : [];
  }

  get id() {
    return this._id;
  }

  get question() {
    return this._question;
  }

  set rating(rating) {
    return this._ratings.push(rating);
  }

  get ratings() {
    return this._ratings;
  }

  get answers() {
    return this._answers;
  }

  set answers(answer) {
    return this._answers.push(answer);
  }

  get categories() {
    return this._categories;
  }

  set categories(category) {
    return this._categories.push(category);
  }

  mapToModel() {
    return {
      question_id: this.id,
      question: this.question,
      answers: this.answers,
      categories: this.categories,
      ratings: this.ratings,
    };
  }
}

module.exports = Question;
